#
---
apiVersion: v1
kind: Template
metadata:
  name: idmsvc-frontend
  # https://kubernetes.io/docs/reference/labels-annotations-taints/
  annotations:
    kubernetes.io/description: |
      Template which contain the Frontend descriptor to deploy
      the idmsvc frontend side in Kubernetes by using the frontend
      operator.

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: ${APP_NAME}
    spec:
      envName: ${ENV_NAME}
      title: "Directory and Domain Services"
      deploymentRepo: https://github.com/podengo-project/idmsvc-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/${APP_NAME}
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "${APP_NAME}"
          title: "Directory and Domain Services"
          href: "/settings/${APP_NAME}"
          product: "Red Hat Insights"
      module:
        manifestLocation: "/apps/${APP_NAME}/fed-mods.json"
        modules:
          - id: "${APP_NAME}"
            module: "./RootApp"
            routes:
              - pathname: "/settings/${APP_NAME}"

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: "quay.io/cloudservices/idmsvc-frontend"
  - name: APP_NAME
    value: idmsvc
